/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governanceSol from "./Governance.sol";
export type { governanceSol };
import type * as timelockSol from "./Timelock.sol";
export type { timelockSol };
